version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s | %(levelname)s | %(name)s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    (): logging.StreamHandler
    level: DEBUG
    formatter: simple

loggers:
  main:
    handlers: [console]
    level: DEBUG
    propagate: False
