version: 1
disable_existing_loggers: False

formatters:
  custom:
    class: main.helpers.logger_formatters.CustomFormatter
    format: '%(asctime)s | %(name)s | %(levelname)s | %(context_user)s | %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%SZ'

handlers:
  custom:
    class: main.helpers.logger_handlers.CustomHandler
    level: DEBUG
    formatter: custom

loggers:
  main:
    handlers: [custom]
    level: DEBUG
    propagate: False
