version: 1
disable_existing_loggers: False

filters:
  context_injector:
    (): main.helpers.logger_filters.ContextInjectionFilter

formatters:
  custom:
    (): main.helpers.logger_formatters.CustomFormatter
    format: '%(asctime)s | %(levelname)s | %(context_user)s | %(name)s | %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%SZ'

handlers:
  custom:
    (): main.helpers.logger_handlers.CustomHandler
    level: DEBUG
    filters: [context_injector]
    formatter: custom

loggers:
  main:
    handlers: [custom]
    level: DEBUG
    propagate: False
